id: IC18C9B41
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:26:12+00:00'
last_modified: '2022-06-08T09:21:58.219198+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22088
  title: མཉམ་མེད་སྒམ་པོ་པའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9B34:
      image_group_id: I1GS105470
      title: ''
      total_pages: 198
      order: 1
      base_file: 9B34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
