id: P009205
initial_creation_type: ocr
source_metadata:
  id: bdr:W22088
  title: མཉམ་མེད་སྒམ་པོ་པའི་རྣམ་ཐར
  author: ''
  volumes:
    15f75bc503b04dfa820c5d8de169dec9:
      image_group_id: I1GS105470
      title: ''
      volume_number: 1
      total_pages: 198
