id: P009205
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:58.661338
source_metadata:
  id: bdr:W22088
  title: མཉམ་མེད་སྒམ་པོ་པའི་རྣམ་ཐར
  author: ''
  volumes:
    15f75bc503b04dfa820c5d8de169dec9:
      image_group_id: I1GS105470
      title: ''
      volume_number: 1
      total_pages: 198
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
